version: "3.9"

services:

  postgres:
    image: postgres:15.15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10.15.0
    container_name: flyway_migration
    depends_on:
      - postgres
    command: >
      -url=jdbc:postgresql://postgres:5432/app_db
      -user=app_user
      -password=app_pass
      migrate
    volumes:
      - ./db/migration:/flyway/sql

  app:
    build: (NOME DA SUA IMAGEM GERADA)
    container_name: spring_app
    depends_on:
      - postgres
      - flyway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
